- README.md
Clean up of links to point to new docs site, trace description
> Updating links/tracing description

- examples/agent_patterns/README.md
Link to input and output guardrails examples.
> Fix guardrails examples link

- examples/tools/computer_use.py
- pyproject.toml
- src/agents/_run_impl.py
- src/agents/items.py
- src/agents/models/openai_responses.py
- src/agents/tool.py
- tests/test_items_helpers.py
- tests/test_openai_responses_converter.py
- tests/test_run_step_processing.py
- uv.lock
- **pin to openai 1.66.2, update tests**
- **make computer use example less verbose**
> Bump open AI sdk version

- docs/multi_agent.md
Fix: Multi-agent design patterns link in documentation
This PR fixes the broken link to the examples/agent_patterns directory in the multi_agent.md documentation file. The previous link was missing the /tree/main/ path component required by GitHub for directory navigation.
Changes made:
Updated the link from https://github.com/openai/openai-agents-python/examples/agent_patterns to https://github.com/openai/openai-agents-python/tree/main/examples/agent_patterns
> Fix: Multi-agent design patterns link

- docs/config.md
- docs/guardrails.md
- docs/tracing.md
I updated some documentation typos:
- Corrected spelling in config.md: "chnage" -> "change"
- Fixed typo in guardrails.md: "guardrailas" -> "guardrails"
- Corrected spelling in tracing.md: "Optiona" -> "Optional"
> fix: correct typos in general documentation

- docs/multi_agent.md
I fixed a logical contradiction in multi_agent.md where "orchestrating via LLM" was incorrectly used twice in the same sentence under the "Orchestrating via code" heading.
> fix: clarify multi-agent orchestration description

- README.md
- docs/results.md
- examples/research_bot/README.md
I updated some documentation typos:
- Corrected spelling of "messages" in README.md **("messsages" → "messages")**
- Fixed "occurred" spelling in results.md **("occured" → "occurred")**
- Corrected "it's" to "its" in research_bot README **("it's" → "its")**
> docs: Fix typos in documentation files

- src/agents/tracing/processors.py
Closes #53 
Counts the number of `spans` and `traces` correctly to show the correct number in the debug logs.
> fix: count `spans` and `traces` correctly

- docs/models.md
"The Agents SDK comes with out of the box support" → "The Agents SDK comes with out-of-the-box support" (Hyphenate "out-of-the-box" as it's a compound adjective).
"Sets the the name of an OpenAI model directly." → "Sets the name of an OpenAI model directly." (Remove the duplicate "the").
"While our SDK supports both the [OpenAIResponsesModel][agents.models.openai_responses.OpenAIResponsesModel] and the[OpenAIChatCompletionsModel]" → "While our SDK supports both the [OpenAIResponsesModel][agents.models.openai_responses.OpenAIResponsesModel] and the [OpenAIChatCompletionsModel] (Add missing space after "the").
> Fix typo in models.md

- README.md
"We process the tool calls (if any) and append the tool responses messsages."
→ "We process the tool calls (if any) and append the tool response messages." (typo: "messsages" → "messages")
"If the response has a final output (see below for the more on this), we return it and end the loop."
→ "If the response has a final output (see below for more on this), we return it and end the loop." (remove "the")
> fix: correct typo in README regarding tool responses

- src/agents/models/openai_chatcompletions.py
- tests/test_openai_chatcompletions_converter.py
The Agents SDK currently rejects messages with the 'assistant' role when processing conversation histories. Specifically, the _Converter.items_to_messages method raises a UserError with the message "Unexpected role in easy_input_message: assistant". This affects both direct usage of the converter and higher-level APIs like Runner.run_sync.
This is a critical issue because the 'assistant' role is a standard part of the OpenAI Chat Completions API and must be supported for building conversational agents that maintain context across multiple turns. Currently, any attempt to process a conversation history containing assistant responses fails, breaking functionality for many common use cases.
[Reproducible Example Code - Failing Case]
```python
from agents.models.openai_chatcompletions import …
```
> Fix: Add missing support for 'assistant' Role in Converter.items_to_messages used by Runner.run_sync

- src/agents/guardrail.py
> chore: update guardrail.py

- docs/running_agents.md
Corrected the variable name from 'output' to 'result' in the code snippet in [running_agents.md](https://github.com/openai/openai-agents-python/blob/main/docs/running_agents.md)  to match the actual code usage.
the variable `output` was not defined and it is implying the variable `result` from the first run. 
```
async def main():
agent = Agent(name="Assistant", instructions="Reply very concisely.")
with trace(workflow_name="Conversation", group_id=thread_id):
result = await Runner.run(agent, "What city is the Golden Gate Bridge in?")
print(result.final_output)
new_input = output.to_input_list() + [{"role": "user", "content": "What state is it in?"}]
result = await Runner.run(agent, new_input)
print(result.final_output)
```
```
async def main():
agent = Agent(name="Assistant", …
```
> Replace undefined variable name in documentation code snippet

- examples/agent_patterns/input_guardrails.py
Remove the `not` keyword from the `tripwire_triggered` parameter in the `math_guardrail` function in `examples/agent_patterns/input_guardrails.py`.
The not keyword prevented the guardrail from being triggered, which defeats the purpose of the example.
> Fix guardrail trigger in input_guardrails.py

- src/agents/models/openai_chatcompletions.py
- tests/test_openai_chatcompletions_stream.py
Closes #63. Fixes the type errors with usage, which were hidden away by using model_copy. 
Added a unit test, which failed before and passes now.
Also ran stream_text.py, with chat completions.
> Fix streaming in chat completions

- README.md
- docs/tracing.md
Incredibly excited to add Scorecard as an external trace processor for the Agents SDK!
> Add Scorecard as supported external trace processors

- docs/models.md
- examples/model_providers/README.md
- examples/model_providers/custom_example_agent.py
- examples/model_providers/custom_example_global.py
- examples/model_providers/custom_example_provider.py
- src/agents/__init__.py
- src/agents/_config.py
- src/agents/models/openai_provider.py
Did a few things:
1. Lazy loaded the client in OpenAIProvider so that we don't raises errors in cases where you dont have an openai key, but an OpenAIProvider() is created.
2. Added docs and examples for custom model providers.
Test plan:
```bash
export EXAMPLE_BASE_URL="..."
export EXAMPLE_API_KEY="..."
export EXAMPLE_MODEL_NAME"..."
```
Then run the examples, e.g.:
```bash
python examples/model_providers/custom_example_provider.py
Loops within themselves,
Function calls its own being,
Depth without ending.
```
> Add examples and documentation for using custom model providers

- examples/model_providers/custom_example_agent.py
- examples/model_providers/custom_example_global.py
- examples/model_providers/custom_example_provider.py
- uv.lock
Some users reported issues in #106 with tools, so testing it out here.
Test plan:
- Tested with anthropic (claude-3-7-sonnet-20250219)
- Tested with togetherai (meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo)
> Update custom models to use tools

- docs/models.md
These are common issues faced by devs, so adding docs to help.
> Update model docs with common issues

- src/agents/__init__.py
- src/agents/tracing/create.py
- src/agents/tracing/processors.py
- src/agents/tracing/scope.py
- src/agents/tracing/setup.py
- src/agents/tracing/spans.py
- src/agents/tracing/traces.py
Results in double logging if we dont. Closes #141.
> Consolidate to one logger

- src/agents/function_schema.py
- src/agents/tool.py
- tests/test_function_tool_decorator.py
This PR introduces a `strict_mode: bool = True` option to `@function_tool`, allowing optional parameters when set to False. This change enables more flexibility while maintaining strict JSON schema validation by default.
resolves #43 
- Added `strict_mode` parameter to `@function_tool` and passed it to `function_schema` and `FunctionTool`.
- Updated `function_schema.py` to respect `strict_mode` and allow optional parameters when set to False.
- Added unit tests to verify optional parameters work correctly, including multiple optional params with different types.
- Verified function calls with missing optional parameters behave as expected.
- Added async tests to validate behavior under different configurations.
> feat: Add strict_mode option to function_schema and function_tool

- examples/agent_patterns/input_guardrails.py
- examples/agent_patterns/llm_as_a_judge.py
I think we need to put reasoning-related outputs first to encourage CoT reasoning.
> fix reasoning order in examples

- docs/tracing.md
Hi team! Congrats on the new Agents SDK launch!
This PR adds MLflow to the tracing documentation, as it supports automatic tracing for OpenAI Agents SDK. It has also been supporting tracing for [Swarm](https://mlflow.org/docs/latest/tracing/integrations/swarm) as well, so it is fantastic that the new SDK offers built-in mechanism for 3P trace providers🙂
> [doc] add mlflow tracing integration

- .github/workflows/tests.yml
- Makefile
Run the tests with `coverage`, and make sure the min coverage is 95%.
> Add min 95% code coverage

- src/agents/tool.py
- tests/test_function_tool_decorator.py
As titled. Test plan: unit tests/docs.
> Update tests and docs for strict mode decorator

- docs/agents.md
- examples/agent_patterns/forcing_tool_use.py
- examples/basic/tools.py
- src/agents/__init__.py
- src/agents/_run_impl.py
- src/agents/agent.py
- src/agents/items.py
- src/agents/tool.py
- src/agents/tracing/span_data.py
- tests/test_agent_runner.py
- tests/test_function_tool.py
- tests/test_tool_use_behavior.py
By default, the outputs of tools are sent to the LLM again. The LLM gets to read the outputs, and produce a new response. There are cases where this is not desired:
1. Every tool results in another round trip, and sometimes the output of the tool is enough.
2. If you force tool use (via model settings `tool_choice=required`), then the agent will just infinite loop.
This enables you to have different behavior, e.g. use the first tool output as the final output, or write a custom function to process tool results and potentially produce an output.
Added new tests and ran existing tests
Also added examples.
Closes #117
> Introduce tool_use_behavior on agents

- docs/examples.md
- mkdocs.yml
Have gotten feedback that Examples are somewhat buried in the Github docs. Adding new page after quickstart.
> add examples section to docs

- examples/financial_research_agent/README.md
- examples/financial_research_agent/agents/financials_agent.py
- examples/financial_research_agent/agents/planner_agent.py
- examples/financial_research_agent/agents/risk_agent.py
- examples/financial_research_agent/agents/search_agent.py
- examples/financial_research_agent/agents/verifier_agent.py
- examples/financial_research_agent/agents/writer_agent.py
- examples/financial_research_agent/main.py
- examples/financial_research_agent/manager.py
- examples/financial_research_agent/printer.py
This example shows how you might compose a richer financial research agent using the Agents SDK. The pattern is similar to the `research_bot` example, but with more specialized sub‑agents and a verification step.
The flow is:
1. **Planning**: A planner agent turns the end user’s request into a list of search terms relevant to financial analysis – recent news, earnings calls, corporate filings, industry commentary, etc.
2. **Search**: A search agent uses the built‑in `WebSearchTool` to retrieve terse summaries for each search term. (You could also add `FileSearchTool` if you have indexed PDFs or 10‑Ks.)
3. **Sub‑analysts**: Additional agents (e.g. a fundamentals analyst and a risk analyst) are exposed as tools so the writer can call them inline and incorporate their outputs.
4. …
> Adds example for financial agent

- src/agents/tracing/processors.py
- tests/tracing/test_processor_api_key.py
A common complaint is that people load their API keys using dotenv:
```
import agents # imports tracing by default
load_dotenv()
```
This causes issues, because by the time you load your dotenv, the batch processor has already read the API key.
Let's lazy load it, so it's deferred to when the processor actually _needs_ the key.
> Read tracing API data lazily

- docs/context.md
Fix inconsistent numbering between code and explanatory annotations in the context management documentation.
> [docs] fix annotation numbering in context management

- src/agents/tracing/processors.py
1. Make it clear it's non-fatal
2. Make it clear it's a tracing error
> Improve tracing error messages

- .gitignore
Uncomment .idea/ directory in .gitignore to ensure PyCharm IDE project configuration files are excluded from version control.
> chore: ignore PyCharm .idea/ directory

- .github/workflows/tests.yml
- Makefile
We don't really need mypy on 3.9 (unit tests would catch any real issues), and it causes issues with the rest of this stack.
---
* #324
* #322
* #321
* #320
* __->__ #319
> [0/n] Only run tests on py3.9, not mypy

- src/agents/models/openai_responses.py
Currently, when we set `parallel_tool_calls=False` in the `model_settings`, the responses API is called with `parallel_tool_calls == NotGiven`, which defaults to true on the Response API side (https://platform.openai.com/docs/api-reference/responses/create#responses-create-parallel_tool_calls).
This PR attempts to fix that.
```
agent = Agent(
...,
model_settings=ModelSettings(
parallel_tool_calls=False,
),
)
```
> Fix parallel_tool_calls when False

- pyproject.toml
- src/agents/mcp/__init__.py
- src/agents/mcp/mcp_util.py
- src/agents/mcp/server.py
- src/agents/mcp/util.py
- uv.lock
1. Add the MCP dep for python 3.10, since it doesn't support 3.9 and below
2. Create MCPServer, which is the agents SDK representation of an MCP server
3. Create implementations for HTTP-SSE and StdIO servers, directly copying the [MCP SDK example](https://github.com/modelcontextprotocol/python-sdk/blob/main/examples/clients/simple-chatbot/mcp_simple_chatbot/main.py)
4. Add a util to transform MCP tools into Agent SDK tools
Note: I added optional caching support to the servers. That way, if you happen to know a server's tools don't change, you can just cache them.
Checks pass. I added tests at the end of the stack.
--- 
#324
#322
#321
-> #320
#319
> [1/n] Add MCP types to the SDK

- examples/mcp/filesystem_example/README.md
- examples/mcp/filesystem_example/main.py
- examples/mcp/filesystem_example/sample_files/favorite_books.txt
- examples/mcp/filesystem_example/sample_files/favorite_cities.txt
- examples/mcp/filesystem_example/sample_files/favorite_songs.txt
Spins up a stdio server with some local files, then asks the model questions.
Run the example, see it work.
(repeat of #322)
> [3/n] Add an MCP stdio example

- docs/agents.md
- src/agents/_run_impl.py
- src/agents/agent.py
- src/agents/models/openai_responses.py
- src/agents/run.py
- tests/fake_model.py
- tests/test_tool_choice_reset.py
#263 added this behavior. The goal was to prevent infinite loops when tool choice was set. The key change I'm making is:
1. Making it configurable on the agent.
2. Doing bookkeeping in the Runner to track this, to prevent mutating agents.
3. Not resetting the global tool choice in RunConfig.
Unit tests.
.
> Make the reset behavior on tool use configurable

- examples/voice/static/main.py
- examples/voice/static/util.py
Previously the stream was closing as soon as all the audio was added but didn't wait for it to be finished. Additionally the audio might seem chopped off if there is no additional silence so this PR also adds one second of silence before exiting the program.
> fix(examples): make sure audio playback finishes

- src/agents/_run_impl.py
- tests/test_tracing_errors.py
- tests/test_tracing_errors_streamed.py
Also includes the set of requested agents in the error data.
> Mark handoff span as errored when multiple handoffs are requested

- examples/mcp/filesystem_example/README.md
- examples/mcp/git_example/README.md
- examples/mcp/git_example/main.py
- examples/mcp/sse_example/README.md
- examples/mcp/sse_example/main.py
- examples/mcp/sse_example/server.py
Simple example with a local SSE server.
> MCP example for SSE

- src/agents/strict_schema.py
- tests/test_function_schema.py
Towards #345
Using a `dict` or `Mapping` isn't strict-mode compliant. But we were checking for the literal `True` whereas the value can also be an array, for example. Fix that.
Unit tests
> Raise error on more invalid function schemas

- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
- tests/test_agent_runner.py
- tests/test_openai_chatcompletions.py
Closes https://github.com/openai/openai-agents-python/issues/173
This will also set stored completions to True by default, encouraging a best practice.
> Expose the "store" parameter through ModelSettings

- docs/tracing.md
Per discussions with @dmitri-openai , a PR to add a link to Databricks hosted MLflow for tracing integrations
> Databricks MLflow tracing integration

- src/agents/tracing/processors.py
fix duplicate declaration of _shutdown_event
reported by issue https://github.com/openai/openai-agents-python/issues/314
> fix duplicate declaration of _shutdown_event

- src/agents/agent.py
This pull request fixes docstring in `ToolsToFinalOutputFunction`, where `ToolToFinalOutputResult` was incorrectly referenced instead of `ToolsToFinalOutputResult`.
- Updated the docstring of `ToolsToFinalOutputFunction` to correctly reference `ToolsToFinalOutputResult`.
```python
"""A function that takes a run context and a list of tool results, and returns a
`ToolToFinalOutputResult`.
"""
```
```python
"""A function that takes a run context and a list of tool results, and returns a
`ToolsToFinalOutputResult`.
"""
```
- The incorrect reference could cause confusion for developers reading the code.
- This aligns the documentation with the actual return type of the function.
This is a documentation-only change and does not affect runtime behavior.
- Please review for accuracy in …
> Fix Docstring Reference in 'ToolsToFinalOutputFunction' in 'agent.py'

- src/agents/models/openai_chatcompletions.py
Resolves #419. Unclear why, but `""` was raising errors.
Confirmed things work with openai and anthropic both.
> Use "{}" instead of empty string for arguments

- .vscode/settings.json
- pyproject.toml
- src/agents/__init__.py
- src/agents/version.py
- tests/test_function_tool_decorator.py
- uv.lock
Summary:
1. Use <2 for MCP version so it doesn't break if the MCP sdk upgrades.
2. Test the func schema extraction logic.
3. Fix the logic to get the version nuber of the framework
Test Plan:
unit tests
> Misc small fixes - mcp version, test for function_schema, version gen

- docs/running_agents.md
Group ID is being mistakenly referenced as Session ID, which is a bit confusing.
> Fix reference to group id as session id

- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
Allows metadata to be supplied to the `responses.create` call. This can, for example, be used to connect response logs to traces groups by passing the group_id.
> Add metadata to ModelSettings

- src/agents/mcp/util.py
- tests/mcp/test_mcp_util.py
Resolves #449 - TLDR, [OpenAI's API](https://platform.openai.com/docs/api-reference/responses/create) expects the properties field to be present, whereas the MCP schema explicitly allows omitting the properties field. [MCP Spec](https://github.com/modelcontextprotocol/specification/blob/main/schema/2025-03-26/schema.json)
> Ensure MCP works when inputSchema.properties is missing

- examples/tools/computer_use.py
Updated the `computer-use` example to support simultaneous key presses.  
The current implementation presses and releases keys one at a time, which prevents combo inputs like copy (CTRL+C) from working correctly.
N/A
N/A
> Update `computer-use` example to support simultaneous key presses

- examples/research_bot/agents/search_agent.py
Thanks to awesome example `research_bot`
Fix andproduce and goodgrammar (and so on)
```python
>>> from examples.research_bot.agents import search_agent
>>> print(search_agent.INSTRUCTIONS)
You are a research assistant. Given a search term, you search the web for that term andproduce a concise summary of the results. The summary must 2-3 paragraphs and less than 300words. Capture the main points. Write succinctly, no need to have complete sentences or goodgrammar. This will be consumed by someone synthesizing a report, so its vital you capture theessence and ignore any fluff. Do not include any additional commentary other than the summaryitself.
```
> examples(research_bot): Add space to INSTRUCTIONS

- src/agents/tracing/scope.py
- src/agents/tracing/span_data.py
Built docs and tested outputs locally
> Adding scope and span_data doc strings

- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- tests/test_openai_chatcompletions.py
fix issue https://github.com/openai/openai-agents-python/issues/442
below is an example to overwrite include_usage
```
result = Runner.run_streamed(
agent,
"Write a haiku about recursion in programming.",
run_config=RunConfig(
model_provider=CUSTOM_MODEL_PROVIDER,
model_settings=ModelSettings(include_usage=True)
),
)
```
> add overwrite mechanism for stream_options

- docs/ja/models.md
- docs/models.md
This is a pretty minor improvement to the docs: `model_settings` parameter is only mentioned on the agent doc page, but first-time visitors may want to know it’s also available on the models page.
> Add model_settings guide to models document page

- src/agents/models/openai_responses.py
ensure metadata is non-null in response handling
> fix: ensure metadata is non-null in response handling

- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
Added the possibility to pass `extra_query` and `extra_body` parameters when sending a request.
In this implementation I added the attributes to `ModelSettings` as suggested by @rm-openai in #487 .
I'll be happy to add some tests if you have any suggestions.
> Add extra request parameters `extra_query` and `extra_body`

- docs/scripts/translate_docs.py
- src/agents/function_schema.py
- src/agents/tracing/span_data.py
- tests/test_agent_hooks.py
Detected typos using typos-cli (https://crates.io/crates/typos-cli). It detected "occured" in a string constant "handoff_occured" too, but I didn't change the part this time because it could be a minor breaking change.
Full outputs:
```
% typos .
error: `Supresses` should be `Suppresses`
--> ./src/agents/function_schema.py:134:7
|
134 |     # Supresses warnings about missing annotations for params
|       ^^^^^^^^^
|
error: `typ` should be `typo`, `type`
--> ./src/agents/strict_schema.py:51:5
|
51 |     typ = json_schema.get("type")
|     ^^^
|
error: `typ` should be `typo`, `type`
--> ./src/agents/strict_schema.py:52:8
|
52 |     if typ == "object" and "additionalProperties" not in json_schema:
|        ^^^
|
error: `typ` should be `typo`, `type`
--> ./src/agents/strict_schema.py:55:9
| …
```
> Fix typos and misspellings

- examples/agent_patterns/streaming_guardrails.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
An example for the question in the issue attached - how to run guardrails during streaming.
Towards #495.
> Example for streaming guardrails

- src/agents/items.py
- src/agents/models/interface.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
- src/agents/result.py
- src/agents/run.py
- tests/fake_model.py
- tests/test_items_helpers.py
- tests/test_openai_chatcompletions.py
- tests/test_openai_chatcompletions_stream.py
- tests/test_responses_tracing.py
- tests/test_run_step_execution.py
- tests/test_run_step_processing.py
- tests/voice/test_workflow.py
Allows passing in the previous_response_id to reduce sending the same data again and again.
Test plan:
Examples. Adding tests in next PR shortly.
---
* __->__ #509
* #508
> Previous response id

- src/agents/models/openai_chatcompletions.py
The current ChatCompletion API supports only `parallel_tool_calls=True` or `parallel_tool_calls=NOT_GIVEN`
This PR is to support setting `parallel_tool_calls=False`, a common requirement in controlling agent tool use patterns (e.g. ensuring one tool call at the time, to facilitate desired tool calling sequence).
I followed the merged [PR#333](https://github.com/openai/openai-agents-python/pull/333) for consistency.
> Support parallel_tool_calls=False for ChatCompletion API

- examples/basic/previous_response_id.py
- tests/fake_model.py
- tests/test_agent_runner.py
> Examples and tests for previous_response_id

- examples/model_providers/litellm_provider.py
- pyproject.toml
- src/agents/extensions/models/litellm_model.py
- src/agents/models/chatcmpl_helpers.py
- tests/test_function_schema.py
- tests/test_openai_chatcompletions.py
- tests/voice/conftest.py
- uv.lock
litellm is a library that abstracts away details/differences for a lot of model providers. Adding an extension, so that any provider can easily be integrated.
---
* #532
* __->__ #524
> Litellm integration

- examples/basic/non_strict_output_type.py
- src/agents/__init__.py
- src/agents/_run_impl.py
- src/agents/agent.py
- src/agents/agent_output.py
- src/agents/extensions/models/litellm_model.py
- src/agents/models/chatcmpl_converter.py
- src/agents/models/interface.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
- src/agents/result.py
- src/agents/run.py
- tests/fake_model.py
- tests/test_agent_config.py
- tests/test_openai_chatcompletions_converter.py
- tests/test_openai_responses_converter.py
- tests/test_output_tool.py
- tests/voice/test_workflow.py
See #528, some folks are having issues because their output types are not strict-compatible.
My approach was:
1. Create `AgentOutputSchemaBase`, which represents the base methods for an output type - the json schema + validation
2. Make the existing `AgentOutputSchema` subclass `AgentOutputSchemaBase`
3. Allow users to pass a `AgentOutputSchemaBase` to `Agent(output_type=...)`
> Enable non-strict output types

- .gitignore
- pyproject.toml
- src/agents/result.py
- src/agents/run.py
- tests/fastapi/streaming_app.py
- tests/fastapi/test_streaming_context.py
- uv.lock
Closes #435 and closes #538.
Unit tests.
> Start and finish streaming trace in impl metod

- examples/model_providers/litellm_auto.py
- src/agents/extensions/models/litellm_provider.py
- src/agents/models/multi_provider.py
- src/agents/run.py
This replaces the default model provider with a `MultiProvider`, which has the logic:
- if the model name starts with `openai/` or doesn't contain "/", use OpenAI
- if the model name starts with `litellm/`, use LiteLLM to use the appropriate model provider.
It's also extensible, so users can create their own mappings. I also imagine that if we natively supported Anthropic/Gemini etc, we can add it to MultiProvider to make it work.
The goal is that it should be really easy to use any model provider. Today if you pass `model="gpt-4.1"`, it works great. But `model="claude-sonnet-3.7"` doesn't. If we can make it that easy, it's a win for devx.
I'm not entirely sure if this is a good idea - is it too magical? Is the API too reliant on litellm? Comments welcome.
For now, the example. Will add …
> RFC: automatically use litellm if possible

- src/agents/result.py
- tests/test_cancel_streaming.py
Fix for #574 
@rm-openai  I'm not sure how to add a test within the repo but I have pasted a test script below that seems to work 
```python
import asyncio
from openai.types.responses import ResponseTextDeltaEvent
from agents import Agent, Runner
async def main():
agent = Agent(
name="Joker",
instructions="You are a helpful assistant.",
)
result = Runner.run_streamed(agent, input="Please tell me 5 jokes.")
num_visible_event = 0
async for event in result.stream_events():
if event.type == "raw_response_event" and isinstance(event.data, ResponseTextDeltaEvent):
print(event.data.delta, end="", flush=True)
num_visible_event += 1
print(num_visible_event)
if num_visible_event == 3:
result.cancel()
if __name__ == "__main__":
asyncio.run(main())
````
> Allow cancel out of the streaming result

- pyproject.toml
- src/agents/extensions/models/litellm_model.py
- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- tests/model_settings/test_serialization.py
- tests/voice/conftest.py
- uv.lock
Now that `ModelSettings` has `Reasoning`, a non-primitive object, `dataclasses.as_dict()` wont work. It will raise an error when you try to serialize (e.g. for tracing). This ensures the object is actually serializable.
> Create to_json_dict for ModelSettings

- src/agents/voice/__init__.py
- src/agents/voice/model.py
When using the voice agent in typed code, it is suboptimal and error prone to type the TTS voice variables in your code independently.
With this commit we are making the type exportable so that developers can just use that and be future-proof.
Example of usage in code:
```
DEFAULT_TTS_VOICE: TTSModelSettings.TTSVoice = "alloy"
...
tts_voice: TTSModelSettings.TTSVoice = DEFAULT_TTS_VOICE 
...
output = await VoicePipeline(
workflow=workflow,
config=VoicePipelineConfig(
tts_settings=TTSModelSettings(
buffer_size=512,
transform_data=transform_data,
voice=tts_voice,
instructions=tts_instructions,
))
).run(audio_input)
```
> Make the TTS voices type exportable

- docs/tracing.md
Hi Team! 
This PR adds FutureAGI to the tracing documentation as one of the automatic tracing processors for OpenAI agents SDK.
> docs: add FutureAGI to tracing documentation

- src/agents/models/chatcmpl_converter.py
When an input image is given as input, the code tries to access the 'detail' key, that may not be present as noted in #159.
With this pull request, now it tries to access the key, otherwise set the value to `None`.
@pakrym-oai  or @rm-openai let me know if you want any changes.
> Fixed a bug for "detail" attribute in input image

- src/agents/extensions/models/litellm_model.py
- tests/models/test_litellm_extra_body.py
**Purpose**  
Allow arbitrary `extra_body` parameters (e.g. `cached_content`) to be forwarded into the LiteLLM call. Useful for context caching in Gemini models ([docs](https://ai.google.dev/gemini-api/docs/caching?lang=python)).
**Example usage**  
```python
import os
from agents import Agent, ModelSettings
from agents.extensions.models.litellm_model import LitellmModel
cache_name = "cachedContents/34jopukfx5di"  # previously stored context
gemini_model = LitellmModel(
model="gemini/gemini-1.5-flash-002",
api_key=os.getenv("GOOGLE_API_KEY")
)
agent = Agent(
name="Cached Gemini Agent",
model=gemini_model,
model_settings=ModelSettings(
extra_body={"cached_content": cache_name}
)
)
> feat: pass extra_body through to LiteLLM acompletion

- src/agents/mcp/server.py
Added the `instructions` attribute to the MCP servers to solve #704 .
Let me know if you want to add an example to the documentation.
> Added mcp 'instructions' attribute to the server

- docs/tracing.md
Use [Galileo SDK ](https://galileo.ai) to trace your agents
Python SDK code:
https://github.com/rungalileo/galileo-python/blob/main/src/galileo/handlers/openai_agents.py
> Add Galileo to external tracing processors list

- src/agents/extensions/models/litellm_model.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
- src/agents/run.py
- src/agents/usage.py
- tests/models/test_litellm_chatcompletions_stream.py
- tests/models/test_litellm_extra_body.py
- tests/test_extra_headers.py
- tests/test_openai_chatcompletions.py
- tests/test_openai_chatcompletions_stream.py
- tests/test_responses_tracing.py
- tests/test_usage.py
PR to enhance the `Usage` object and related logic, to support more granular token accounting, matching the details available in the [OpenAI Responses API](https://platform.openai.com/docs/api-reference/responses) . Specifically, it:
- Adds `input_tokens_details` and `output_tokens_details` fields to the `Usage` dataclass, storing detailed token breakdowns (e.g., `cached_tokens`, `reasoning_tokens`).
- Flows this change through
- Updates and extends tests to match
- Adds a test for the Usage.add method
- Aligns the SDK’s usage with the latest OpenAI responses API Usage object
- Supports downstream use cases that require fine-grained token usage data (e.g., billing, analytics, optimization) requested by startups
> DRAFT: Dev/add usage details to Usage class

- pyproject.toml
- src/agents/models/chatcmpl_stream_handler.py
- src/agents/models/openai_responses.py
- tests/fake_model.py
- tests/test_responses_tracing.py
- tests/voice/test_workflow.py
- uv.lock
---
* #732
* #731
* __->__ #730
> Upgrade openAI sdk version

- src/agents/extensions/visualization.py
- tests/test_visualization.py
- avoid infinite recursion in visualization by tracking visited agents
- test cycle detection in graph utility
- `make mypy`
- `make tests` 
Resolves #668
> Fix visualization recursion with cycle detection

- docs/ja/mcp.md
- docs/ja/tools.md
- docs/mcp.md
- docs/tools.md
- mention MCPServerStreamableHttp in MCP server docs
- document CodeInterpreterTool, HostedMCPTool, ImageGenerationTool and LocalShellTool
- update Japanese translations
> Update MCP and tool docs

- src/agents/models/openai_chatcompletions.py
- tests/test_openai_chatcompletions.py
- avoid AttributeError when Gemini API returns `None` for chat message
- return empty output if message is filtered
- add regression test
- `make format`
- `make lint`
- `make mypy`
- `make tests`
Towards #744
> Fix Gemini API content filter handling

- src/agents/extensions/models/litellm_model.py
Small fix:
Removing `import litellm.types` as its outside the try except block for importing litellm so the import error message isn't displayed, and the line actually isn't needed. I was reproducing a GitHub issue and came across this in the process.
> Small fix for litellm model

- src/agents/handoffs.py
This PR fixes a typo in the assert statement within the `handoff` function in `handoffs.py`, changing `'on_input'` to `'on_handoff`' for accuracy and clarity.   
- Corrected the word “on_input” to “on_handoff” in the docstring.
Clear and correct documentation improves code readability and reduces confusion for users and contributors.
> Fix typo in assertion message for handoff function

- src/agents/stream_events.py
People keep trying to fix this, but its a breaking change.
> Add comment to handoff_occured misspelling

- examples/hosted_mcp/approvals.py
- examples/hosted_mcp/simple.py
- src/agents/_run_impl.py
This pull request resolves #777; If you think we should introduce a new item type for MCP call output, please let me know. As other hosted tools use this event, I believe using the same should be good to go tho.
> Fix #777 by handling MCPCall events in RunImpl

- src/agents/mcp/util.py
The EmbeddedResource from MCP tool call contains a field with type AnyUrl that is not JSON-serializable. To avoid this exception, use item.model_dump(mode="json") to ensure a JSON-serializable return value.
> Ensure item.model_dump only contains JSON serializable types

- src/agents/exceptions.py
- src/agents/extensions/models/litellm_model.py
- src/agents/mcp/server.py
- src/agents/result.py
- src/agents/run.py
- src/agents/voice/model.py
- tests/mcp/test_mcp_tracing.py
- tests/models/test_litellm_extra_body.py
- tests/test_agent_runner.py
- tests/test_agent_runner_streamed.py
- tests/test_run_error_details.py
Towards #767. We were caching the list of tools for an agent, so if you did `agent.tools.append(...)` from a tool call, the next call to the model wouldn't include the new tool. THis is a bug.
Unit tests. Note that now MCP tools are listed each time the agent runs (users can still cache the `list_tools` however).
> Don't cache agent tools during a run

- src/agents/tracing/processors.py
Closes #796. Shouldn't start a busy waiting thread if there aren't any traces.
Test plan
```
import threading
assert threading.active_count() == 1
import agents
assert threading.active_count() == 1
```
> Only start tracing worker thread on first span/trace

- src/agents/_run_impl.py
- src/agents/function_schema.py
- src/agents/run_context.py
- src/agents/tool.py
- src/agents/tool_context.py
- tests/test_function_tool.py
- tests/test_function_tool_decorator.py
- tests/test_responses.py
- tests/test_run_step_execution.py
This PR fixes issue: https://github.com/openai/openai-agents-python/issues/559
By adding the tool_call_id to the RunContextWrapper prior to calling tools. This gives the ability to access the tool_call_id in the implementation of the tool.
> Added support for passing tool_call_id via the RunContextWrapper

- pyproject.toml
- src/agents/mcp/server.py
- uv.lock
I replaced the `timedelta` parameters for MCP timeouts with `float` values, addressing issue #845 .
Given that the MCP official repository has incorporated these changes in [this PR](https://github.com/modelcontextprotocol/python-sdk/pull/941), updating the MCP version in openai-agents and specifying the timeouts as floats should be enough.
> adopted float instead of timedelta for timeout parameters

- src/agents/repl.py
In the REPL utility, the final output was printed after the streaming, causing a duplication issue.
I only removed the lines within the stream mode that printed the final output. It should not affect any other use case of the utility.
It solves a comment done in #784 .
> Removed lines to avoid duplicate output in REPL utility

- .github/workflows/issues.yml
Like I did for the TypeScript SDK project (see https://github.com/openai/openai-agents-js/pull/97), we may want to have the labels to exclude the issues from auto-closing. Some of the issues that have been open for a while could just need time.
> Add exempt-issue-labels to the issue triage GH Action job

- src/agents/models/openai_chatcompletions.py
This pull request resolves #604; just checking the existence of the data and avoiding the runtime exception should make sense.
> Fix #604 Chat Completion model raises runtime error when response.choices is empty

- docs/context.md
This pull request fixes [issue #892](https://github.com/openai/openai-agents-python/issues/892) by adding a missing docstring to the `fetch_user_age` tool function in `docs/context.md`.
Many non-OpenAI LLMs (such as Claude, Gemini, Mistral, etc.) are unable to use the `fetch_user_age` function because it lacks a docstring. As a result, they return responses like:
> "I cannot determine the user's age because the available tools lack the ability to fetch user-specific information."
- Added a one-line docstring to the `fetch_user_age` function
- Improved return statement to match expected tool output
```python
@function_tool
async def fetch_user_age(wrapper: RunContextWrapper[UserInfo]) -> str:
"""Fetch the age of the user. Call this function to get user's age information."""
return f"The …
```
> Fix #892 by adding proper tool description in context.md

- pyproject.toml
Issue: "Intended Audience :: Developers" appears twice in the classifiers list. Line Number 20 and Line Number 26 Fix: Removed the duplicate classifier entry
> Duplicate Classifier in pyproject.toml

- README.md
- Add Option A (venv) and Option B (uv) in Get started section
- Mark uv as recommended to align with development workflow
- Include Windows activation commands for both options
- Resolves #884
> Add uv as an alternative Python environment setup option for issue #884

- src/agents/model_settings.py
Closes #762
**Description**
This PR updates the docstring for the `parallel_tool_calls` attribute in the `ModelSettings` dataclass to accurately reflect its default behavior.. The previous docstring incorrectly stated that the default of `False`, while the actual behavior is dependent on the underlying model provider's default.
As noted in OpenAI's (here refers as model provider) [Function Calling](https://platform.openai.com/docs/guides/function-calling?api-mode=responses#parallel-function-calling) documentation, "The model may choose to call multiple functions in a single turn. You can prevent this by setting parallel_tool_calls to false, which ensures exactly zero or one tool is called."  
Therefore, when the `parallel_tool_calls` attribute in the `ModelSettings` dataclass is set to …
> Fix and Document `parallel_tool_calls` Attribute in ModelSettings

- examples/basic/agent_lifecycle_example.py
- examples/basic/lifecycle_example.py
**Problem:**
The expected output in the agent lifecycle example incorrectly shows agent start hooks (`on_start`) running after tool execution and multiple times for the same agent. This misleads developers about when these lifecycle events actually occur.
**Solution:**
Updated the expected output to accurately reflect the OpenAI Agents framework behavior:
- Agent start hooks run immediately when an agent begins execution
- Start hooks only run once per agent activation, controlled by the `should_run_agent_start_hooks` flag
- After handoffs, the new agent's start hook runs as the first event
> Fix agent lifecycle example output to reflect correct hook execution order

- Makefile
- README.md
It adds a Makefile rule `check` to run all linters and checkers in a single command. 
With only `make check`  instead of 3-4 commands, it can help to forget one of them before pushing a PR.
> Add Makefile check rule to run all the linters and checkers

- src/agents/function_schema.py
Describe the bug
A clear and concise description of what the bug is.
In the function_schema method of the OpenAI Agents SDK, the following line:
```python
description=description_override or doc_info.description if doc_info else None
```
does not honor description_override when `use_docstring_info=False`. This happens because of operator precedence in Python. Without parentheses, the expression is interpreted as:
```python
description=(description_override or doc_info.description) if doc_info else None
```
So when doc_info is None, even if description_override is set, it falls back to None
Debug information
Python version (e.g. Python 3.10)
Repro steps
```python
from agents.function_schema import function_schema
def my_func():
pass
schema = function_schema(
my_func,
description_override …
```
> description_override is not properly used for function_schema.description

- src/agents/realtime/items.py
- src/agents/realtime/transport.py
- src/agents/realtime/transport_events.py
- tests/realtime/test_transport_events.py
Transport interface for actually connecting to the backend and managing realtime conversations. The transport emits events.
---
* #1074
* #1073
* #1072
* __->__ #1071
> [4/n] Transport interface + events

- pyproject.toml
- src/agents/realtime/items.py
- src/agents/realtime/openai_realtime.py
- src/agents/realtime/transport.py
- src/agents/realtime/transport_events.py
- tests/realtime/test_transport_events.py
Uses the openai realtime impl over websockets. Unlike the TS version, only supports websockets - no in browser stuff.
---
* #1074
* #1073
* __->__ #1072
* #1071
> [5/n] OpenAI realtime transport impl

- pyproject.toml
- src/agents/realtime/README.md
- src/agents/realtime/__init__.py
- src/agents/realtime/events.py
- src/agents/realtime/items.py
- src/agents/realtime/openai_realtime.py
- src/agents/realtime/session.py
- src/agents/realtime/transport.py
- src/agents/realtime/transport_events.py
- tests/realtime/test_transport_events.py
RealtimeSession is like Runner, except for Realtime. It's also stateful and manages the conversation for you.
---
* #1076
* #1074
* __->__ #1073
* #1072
* #1071
> [6/n] RealtimeSession + events

- pyproject.toml
- src/agents/model_settings.py
- src/agents/models/chatcmpl_converter.py
- src/agents/models/openai_responses.py
- tests/model_settings/test_serialization.py
- tests/test_items_helpers.py
- tests/test_run_step_processing.py
- uv.lock
This pull request resolves #968
> Fix #968 by upgrading openai package to the latest

- src/agents/realtime/config.py
- src/agents/realtime/model.py
- src/agents/realtime/openai_realtime.py
- src/agents/realtime/runner.py
- tests/realtime/test_tracing.py
Just sends tracing info to the server.
> Realtime tracing

- docs/sessions.md
The previous comments incorrectly suggested that the user's question was removed before the assistant's response. This fix updates the comment order to reflect the actual sequence of the code execution.
> Fix incorrect comment order when popping session items

- src/agents/realtime/events.py
- src/agents/realtime/session.py
- tests/realtime/test_session.py
Guardrails were blocking the event loop. Now, they run as a separate task. 
---
* #1112
* #1111
* #1107
* #1106
* __->__ #1104
> Realtime: run guardrails without blockign event loop

- examples/mcp/prompt_server/main.py
- src/agents/model_settings.py
- src/agents/models/openai_responses.py
- tests/realtime/test_session.py
- tests/realtime/test_tracing.py
cleanup
---
* #1112
* #1111
* #1107
* __->__ #1106
> Run make format

- src/agents/agent.py
- src/agents/tool.py
- tests/test_session_exceptions.py
this PR fixes typos in docstrings and updates the async for loop variable in the test as per review feedback.
fixed typo: ToolToFinalOutputResult -> ToolsToFinalOutputResult
removed duplicate 'a' in docstring
changed async for loop variable from _event to _ in test_session_exceptions.py
> Fix typos and update async for loop variable

- docs/ref/tool_context.md
- docs/tools.md
- mkdocs.yml
- src/agents/_run_impl.py
- src/agents/realtime/session.py
- src/agents/tool_context.py
- tests/test_function_tool.py
- tests/test_function_tool_decorator.py
This is a follow-up to pr #1043   The original changes were reverted due to missing updates in RealtimeSession, which caused runtime test failures.
This PR:
- Reapplies the `tool_name` and `tool_call_id` additions to `ToolContext`.
- Updates `RealtimeSession._handle_tool_call` to instantiate `ToolContext` with `tool_name=event.name` and `tool_call_id=event.call_id`.
- Adjusts tests as needed so that all 533 tests (including old-version Python 3.9) pass cleanly.
Closes #1030
> Retry: Add tool_name to ToolContext for generic tool handlers

- examples/realtime/demo.py
- examples/realtime/no_ui_demo.py
The UI demo is nice, but this let you print more logs to the console (at the cost of being ugly)
> Realtime: introduce a demo without a UI

- src/agents/agent.py
- src/agents/guardrail.py
- src/agents/handoffs.py
- src/agents/models/chatcmpl_converter.py
- src/agents/models/openai_responses.py
- src/agents/realtime/__init__.py
- src/agents/realtime/agent.py
- src/agents/realtime/config.py
- src/agents/realtime/handoffs.py
- src/agents/realtime/openai_realtime.py
- src/agents/realtime/session.py
- tests/realtime/test_realtime_handoffs.py
- tests/realtime/test_session.py
- tests/test_handoff_tool.py
> Realtime: handoffs

- pyproject.toml
- src/agents/mcp/server.py
- src/agents/mcp/util.py
- tests/mcp/helpers.py
- tests/mcp/test_mcp_tracing.py
- uv.lock
MCP recently added `structuredContent` as an additional field in tool results. This lets us use that field when sending the response to the model.
> MCP: add support for tool_result.structuredContent

- docs/realtime/guide.md
- docs/realtime/quickstart.md
- docs/ref/realtime/agent.md
- docs/ref/realtime/config.md
- docs/ref/realtime/events.md
- docs/ref/realtime/runner.md
- docs/ref/realtime/session.md
- mkdocs.yml
- src/agents/realtime/config.py
- src/agents/realtime/items.py
Documentation (both written and code)
> Realtime docs

- .github/workflows/update-docs.yml
This pull request resolves the execution error of #598 CI job. The job pushes the changes directly to the main branch. However, our branch policies do not allow bypassing required checks, so it always fails. This pull request changes its behavior just to create a pull request and then ask humans to review (actually you don't need to check translation results though) and merge it.
> Adjust #598 to only create a PR rather than pushing changes to main branch

- src/agents/models/chatcmpl_stream_handler.py
When using streaming responses, some models or API endpoints may return `usage` fields (`prompt_tokens`, `completion_tokens`, `total_tokens`) as `None` or omit them entirely. The current implementation passes these values directly to the `ResponseUsage` Pydantic model, which expects integers. This causes a validation error:
3 validation errors for ResponseUsage
input_tokens
Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
output_tokens
Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
total_tokens
Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
This PR ensures that all token fields passed to `ResponseUsage` are always integers. If any of the fields are `None` or missing, they …
> fix: ensure ResponseUsage token fields are int, not None (fixes #1179)

- docs/quickstart.md
docs: add missing InputGuardrailTripwireTriggered import to quickstart example
Fixes NameError when handling guardrail exceptions by including the required import in the docs.
> Add missing guardrail exception import to quickstart

- src/agents/tool.py
Fixes an issue where directly created `FunctionTool` objects fail with OpenAI's Responses API due to missing `additionalProperties: false` in the JSON schema, while the `@function_tool` decorator works correctly.
The documentation example for creating `FunctionTool` objects directly fails with:
```
Error code: 400 - {'error': {'message': "Invalid schema for function 'process_user': In context=(), 'additionalProperties' is required to be supplied and to be false.", 'type': 'invalid_request_error', 'param': 'tools[0].parameters', 'code': 'invalid_function_parameters'}}
```
This creates an inconsistency between `FunctionTool` and `@function_tool` behavior, both of which have `strict_json_schema=True` by default.
- Added `__post_init__` method to `FunctionTool` dataclass
- Automatically …
> fix: Apply strict JSON schema validation in FunctionTool constructor

- examples/tools/image_generator.py
Due to the method name typo, it does not work on the OS.
> Fix image_generator example error on Windows OS

- README.md
- Added LiteLLM to the acknowledgements section in README.md
- Recognized LiteLLM as a unified interface for 100+ LLMs, which aligns with the SDK's provider-agnostic approach
> Add LiteLLM to acknowledgements section

- examples/reasoning_content/main.py
The current script gives
```
Traceback (most recent call last):
File "/Users/xmxd289/code/openai-agents-python/examples/reasoning_content/main.py", line 19, in <module>
from agents.types import ResponseOutputRefusal, ResponseOutputText  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'agents.types'
```
because it should be
`from openai.types.responses import ResponseOutputRefusal, ResponseOutputText`
rather than
`from agents.types import ResponseOutputRefusal, ResponseOutputText`
> [Bugfix] Fix wrong imports in examples

- src/agents/realtime/events.py
- src/agents/realtime/model_events.py
- src/agents/realtime/openai_realtime.py
- src/agents/realtime/session.py
- tests/realtime/test_session.py
Will need this for a followup.
---
* #1243
* #1242
* __->__ #1235
> Realtime: send audio item/content index

- src/agents/agent_output.py
Updated the error message to replace the placeholder `your_type` with `YourType`, removing the underscore and adopting PascalCase, which aligns with standard Python type naming conventions.
> Fix type placeholder convention

- src/agents/guardrail.py
✅ The article usage is now grammatically correct with "an" before class names starting with vowel sounds
✅ The possessive form correctly uses "function's name" instead of "function name"
✅ The redundant word "do" has been removed from "to do check" → "to check"
✅ The line length violations (E501) have been resolved with proper docstring formatting
✅ Overall documentation now maintains professional consistency and grammatical accuracy
> Tweak on guardrail docstrings

- examples/financial_research_agent/agents/writer_agent.py
The Financial Research Agent example is broken because it uses the model `gpt-4.5-preview-2025-02-27`. This model has been [removed and is no longer available](https://platform.openai.com/docs/deprecations#2025-04-14-gpt-4-5-preview).
This change follows the recommendation to replace gpt-4.5-preview with gpt-4.1.
> gpt 4.5-preview is removed, use gpt-4.1

- src/agents/agent.py
Added period to 'etc' to make it 'etc.' in tool_use_behavior docstring
> Fix etc. punctuation

- src/agents/tracing/processors.py
Fixed two minor issues:
1. Corrected "wont" to "won't" in BackendSpanExporter's comment about client error handling.
2. Removed unnecessary trailing comma in ConsoleSpanExporter's trace print statement.
These changes improve code readability and documentation accuracy without affecting functionality.
> Fix documentation typo and trailing comma in exporters

- src/agents/tracing/create.py
Removed incorrect reference to a parameter that does not exist in the trace docstring.
This update only affects documentation and has no impact on runtime behavior.
> docs: remove non existent even_if_trace_running mention from trace docstring

- src/agents/extensions/models/litellm_model.py
- src/agents/models/chatcmpl_converter.py
This PR fixes an issue where reasoning content from models accessed via LiteLLM was not being correctly parsed into the `ChatCompletionMessage` format. This was particularly noticeable when using reasoning models.
I am using the `openai-agents-python` library in my project, and it has been incredibly helpful. Thank you for building such a great tool!
My setup uses `litellm` to interface with `gemini-2.5-pro`. I noticed that while the agent could receive a response, the reasoning(thinking) from the Gemini model was lost during the conversion process from the LiteLLM response format to the OpenAI `ChatCompletionMessage` object.
I saw that PR #871 made progress on a similar issue, but it seems the specific response structure from LiteLLM still requires a small adaptation. This fix adds the …
> fix: convert litellm response with reasoning content to openai message

- docs/agents.md
- docs/ja/agents.md
- docs/scripts/generate_ref_files.py
The documentation in docs/agents.md & docs/ja/agents.md contained an inconsistency where the dynamic_instructions function referenced context.context.name, but the UserContext dataclass only defined uid and is_pro_user fields. This would cause a runtime AttributeError when users tried to follow the example.
- Added the missing name: str field to the UserContext dataclass to match what the dynamic_instructions function expects.
- Added name: str field to the UserContext dataclass in the Context section
- Maintained consistency between the dataclass definition and the dynamic instructions example
- Fixed formatting issues in related files
✅ Code formatting passes (make format-check)
✅ Documentation example is now consistent and functional
✅ No runtime errors when following the example
✅ …
> docs: fix UserContext example

- src/agents/tracing/processors.py
The docstring incorrectly mentioned "below a certain threshold" but the actual implementation drains the queue completely regardless of any threshold.
> Fix _export_batches docstring to remove incorrect "threshold" reference

- docs/agents.md
- src/agents/tracing/create.py
Enhances the "Tool Behavior Definitions" documentation to provide clearer
explanations and more robust examples for agent tool usage. Previously,
developers often faced challenges and ambiguity in understanding and implementing
these tool behaviors due to insufficient examples and unclear import paths.
Key improvements in this update include:
- Explicitly defining import paths for `StopAtTools` and `ToolsToFinalOutputFunction`.
- Providing comprehensive and corrected code examples for all `tool_choice` and
`tool_use_behavior` configurations, including `"stop_on_first_tool"`,
`StopAtTools`, and the usage of `ToolsToFinalOutputFunction`.
- Ensuring proper Markdown formatting for code blocks and notes to enhance
readability and accuracy.
This update aims to significantly reduce ambiguity and …
> Enhance Tool Behavior Documentation for Developer Clarity With Examples

- src/agents/realtime/__init__.py
- src/agents/realtime/_default_tracker.py
- src/agents/realtime/_util.py
- src/agents/realtime/model.py
- src/agents/realtime/openai_realtime.py
- tests/realtime/test_agent.py
- tests/realtime/test_conversion_helpers.py
- tests/realtime/test_openai_realtime.py
- tests/realtime/test_playback_tracker.py
So far, we've been assuming that audio is played:
- immediately (i.e. with 0 delay/latency)
- at realtime
This causes issues with our interrupt tracking. The model wants to know how much audio the user has actually heard. For example in a phone call agent, this wouldn't work (bc theres a delay of a few hundred ms between model sending audio and the user hearing it). This PR allows you to pass a playback tracker.
---
* #1252
* #1216
* #1243
* __->__ #1242
> Realtime: enable a playback tracker

- docs/sessions.md
The tags in sessions document page are incomplete.
> Fix tag errors in sessions document page

- examples/handoffs/message_filter.py
- examples/handoffs/message_filter_streaming.py
- src/agents/_run_impl.py
- src/agents/extensions/handoff_filters.py
- src/agents/handoffs.py
- tests/test_agent_runner.py
- tests/test_agent_runner_streamed.py
- tests/test_extension_filters.py
- tests/test_handoff_tool.py
This pull request resolves #1238
> Fix #1238 by enhancing HandoffInputData and enable passing async functions

- src/agents/realtime/config.py
- src/agents/realtime/openai_realtime.py
Unlike `openai-agents-js`, the python agents realtime sdk does not support setting the `speed` argument.
Since the underlying `openai.types.beta.realtime.Session` already supports the it, this is an easy fix.
This PR addresses that and enables settings speed as part of `RealtimeSessionModelSettings` just like it's javascript counterpart.
> Add support to realtime API for setting "speed" of the models responses

- examples/basic/remote_pdf.py
Added a new example to use agent to interact with remote pdf. This example demonstrates how to use the Open AI to understand and summarise content from a remote pdf.
New example: examples/basic/remote_pdf.py
Shows how to integrate file-based content into the agent workflow
Useful for summarising reports, papers, or legal docs hosted online
Helps users extend agent capabilities to real-world document formats
```python
import asyncio
from agents import Agent, Runner
URL = "https://www.berkshirehathaway.com/letters/2024ltr.pdf"
async def main():
agent = Agent(
name="Assistant",
instructions="You are a helpful assistant.",
)
result = await Runner.run(
agent,
[
{
"role": "user",
"content": [{"type": "input_file", "file_url": URL}],
},
{
"role": "user",
"content": "Can you summarize the …
```
> Examples: use agent to interact with Remote PDF Documents

- docs/repl.md
- docs/tracing.md
This Pull Request aims to improve the clarity and user-friendliness of the run_demo_loop utility documentation. While the existing description is accurate, this update refines it to be more accessible for new users and beginners.
*Key improvements in this update:*
* *Expanded Description:* The introductory text now provides a clearer explanation of run_demo_loop's purpose and its benefit for quick, interactive testing.
* *Enhanced Code Comments:* The Python example is now annotated with simple comments that guide the user through each part of the code, explaining what the Agent is and how the loop is started.
* *Structured Explanation:* The description of how run_demo_loop works is reorganized into a more readable and easy-to-digest paragraph. It clearly explains key features like …
> docs: Clarify and enhance run_demo_loop utility documentation for beginners

- .github/workflows/tests.yml
- src/agents/tracing/processors.py
- tests/tracing/test_set_api_key_fix.py
The `BackendSpanExporter.set_api_key()` method was directly assigning to `self.api_key`, which created an instance attribute that permanently shadowed the `@cached_property`. This broke the environment variable fallback mechanism.  
- Clear the cached property if it exists before updating the private attribute  
- This preserves the intended fallback behavior to environment variables  
- Added test to verify environment variable fallback works after calling `set_api_key()`  
- Existing functionality remains unchanged
> Fix set_api_key breaking cached property mechanism

- src/agents/handoffs.py
Removed extra parentheses from a boolean field and replaced the incorrect term non-null with callable in an assertion message to improve readability and accuracy.
> Fix style and wording issues in handoffs.py

- src/agents/items.py
Improved clarity in a multiline docstring in `RunItemBase` by correcting misplaced parentheses.
Also added guards in `ItemHelpers.extract_last_content` and `extract_last_text` to handle empty `message.content` safely and prevent potential `IndexError`.
> Fix docstring formatting and add safe check for empty message content

- docs/visualization.md
- src/agents/extensions/visualization.py
- tests/test_visualization.py
Add nodes and edges for MCP servers in agent visualization. I'm open to suggestions to modify the style of visualizations.
Example graph with MCP server:
> feat(viz): draw MCP servers

- src/agents/realtime/session.py
If you send the tool output, that causes a `response.create` to be sent. But we only want a response created _after_ the session is updated.
Also updated to use the standard transfer message.
> Realtime: send session update before tool response

- examples/customer_service/main.py
faq_lookup_tool to improve keyword detection and support case-insensitive input.
- Baggage: Added "luggage", "carry-on", "hand luggage", "hand carry" etc
- Seats: Added "seating" and similar words
- Wifi: Added "internet", "wireless", "connectivity", "network", "online" etc
- User input is now matched ***input.lowercase()*** regardless of capitalization or not.
- Reduces missed matches and "I don’t know" responses.
- Handles user input more flexibly across different typing styles and words.
This makes the tool more accurate and user-friendly introduce I don't know responses.
> Enhanced FAQ lookup tool in examples/customer_service app

- docs/index.md
- src/agents/lifecycle.py
This PR updates documentation to more accurately reflect the behavior of guardrails and agent lifecycle hooks.
Changed to better reflects that guardrails validate both inputs and outputs.
Corrects the timing description to accurately reflect that the on_tool_start hook runs concurrently with tool execution rather than before it.
> Improve accuracy of guardrails and lifecycle hook descriptions

- examples/basic/simple_gpt_5.py
- src/agents/model_settings.py
- src/agents/models/openai_chatcompletions.py
- src/agents/models/openai_responses.py
- tests/model_settings/test_serialization.py
This pull request resolves #1407 ; the "minimal" reasoning effort param is already supported.
> Fix #1407 Add reasoning.effort="minimal" and "verbosity" params to ModelSettings

- examples/basic/hello_world_gpt_oss.py
This pull request adds a simple gpt-oss example app
> Add a simple gpt-oss example

- examples/basic/agent_lifecycle_example.py
Fixed an ambiguous docstring in the `random_number` function that could lead to confusion about whether the range is inclusive or exclusive of the maximum value.
The random_number function docstring was ambiguous, using "up to the provided maximum" which could be interpreted as either inclusive or exclusive of the maximum value.
The implementation correctly uses `random.randint(0, max)` which generates numbers from 0 to max inclusive, matching the expected behavior based on usage in the example.
Changed the docstring from:
```python
"Generate a random number up to the provided maximum."
```
To:
```python
"Generate a random number from 0 to max (inclusive)."
```
This makes the behavior explicit and eliminates potential confusion for developers using this function.
> Fix: Clarify random_number function docstring for inclusive range

- docs/handoffs.md
This pull request aims to improve the clarity and completeness of the `handoff()` function documentation.
Currently, the `handoff()` function documentation lists several parameters but omits the `is_enabled` parameter, which is present in the underlying source code. This can be confusing for developers trying to dynamically control handoff behavior.
This change adds `is_enabled` to the list of parameters in the documentation, making it easier for users to understand and utilize this feature.The addition will also align the documentation with the actual implementation, enhancing the overall user experience.
> docs: Clarify the `is_enabled` parameter in `handoff()` documentation

- examples/basic/tools.py
Added a missing docstring to the `get_weather` function in the tools example to improve code documentation and tool description.
The `get_weather` function (tool) was missing a docstring, which is important for:
- Function documentation and code clarity
- Tool description that the LLM uses to understand when to call the tool
- Following Python best practices for function documentation
Just added a clear and concise docstring to the `get_weather` function:
```python
@function_tool
def get_weather(city: str) -> Weather:
"""Get the current weather information for a specified city."""
print("[debug] get_weather called")
return Weather(city=city, temperature_range="14-20C", conditions="Sunny with wind.")
```
This docstring provides a clear description of the function's purpose and helps both …
> Docs: Add missing docstring to get_weather function

- docs/agents.md
Clarified the OpenAI Agents SDK documentation on guardrails to indicate that they apply to both user input and the agent's output, preventing misunderstandings about their scope.
The existing documentation stated:
> "Guardrails allow you to run checks/validations on user input, in parallel to the agent running. For example, you could screen the user's input for relevance."
This wording implied that guardrails are only applicable to **user input**, omitting the fact that they can also run on **agent output**. This could mislead developers into underutilizing guardrails for output validation and filtering.
Updated the documentation sentence from:
> Guardrails allow you to run checks/validations on user input, in parallel to the agent running. For example, you could screen the user's input …
> Docs: Clarify that guardrails apply to both user input and agent output

- examples/basic/stream_items.py
Added a missing docstring to the `how_many_jokes` function in the `stream_items` example to improve code documentation and tool description.
The `how_many_jokes` function was missing a docstring, which is important for:
- Function documentation and code clarity
- Tool description that the LLM uses to understand when to call the tool
- Following Python best practices for function documentation
Added a clear and precise docstring to the `how_many_jokes` function:
```python
def how_many_jokes() -> int:
"""Return a random integer of jokes to tell between 1 and 10 (inclusive)."""
return random.randint(1, 10)
```
The docstring provides a clear description of the function's purpose and helps both developers and LLMs understand when and how to use this tool.
> Docs: Add missing docstring to how_many_jokes tool

- src/agents/run.py
- tests/test_call_model_input_filter.py
- tests/test_call_model_input_filter_unit.py
Some customers have reported that the agent loop can go on for a long time and use up the entire context window. This PR allows modifying the data sent to the model.
> Allow modifying the input sent to the model

- docs/tools.md
- examples/agent_patterns/agents_as_tools_conditional.py
- src/agents/agent.py
- tests/test_agent_as_tool.py
Adds `is_enabled` parameter to `Agent.as_tool()` method for conditionally enabling/disabling agent tools at runtime. Supports boolean values and callable functions for dynamic tool filtering
in multi-agent orchestration.
- Added unit tests in `tests/test_agent_as_tool.py`
- Added example in `examples/agent_patterns/agents_as_tools_conditional.py`
- Updated documentation in `docs/tools.md`
- All tests pass
Closes #1097
> Add conditional tool enabling feature to agent as tool.

- docs/usage.md
- examples/basic/usage_tracking.py
- mkdocs.yml
This PR adds a new documentation page explaining how to access and use token usage data from agent runs. It covers how to get usage data after a run, how it accumulates with sessions, and how to access it in hooks.
> Add documentation for token usage tracking

- examples/tools/web_search_filters.py
- src/agents/model_settings.py
- src/agents/models/openai_responses.py
- src/agents/tool.py
- tests/test_openai_responses_converter.py
This pull request resolves #1592
> Fix #1592 Web search tool updates

- examples/model_providers/litellm_auto.py
- src/agents/_run_impl.py
This pull request improves the interoperability with LiteLLM for structured output use cases (at least with Claude models). I found that LiteLLM could append non-existent tool called "json_tool_call" to handle JSON schema response format. Currently, Agents SDK raises an exception telling the "json_tool_call" tool does not exist, but allowing this tool use simply enables the use case without any issues. I think it's okay for us to add additional logic like this PR does. It's safe and does not break anything.
> Handle LiteLLM's json_tool_call addition for structured outputs

- examples/reasoning_content/gpt_oss_stream.py
- src/agents/models/chatcmpl_stream_handler.py
Since TS SDK has its own protocol layer, the way to handle data is a bit different but this aligns with https://github.com/openai/openai-agents-js/pull/292
> Add reasoning text delta event support for gpt-oss models

- docs/realtime/guide.md
fixed_typo: wiht -> with  in Core Components section
> fixed_typo: wiht -> with

- examples/basic/lifecycle_example.py
- src/agents/run.py
- tests/test_run_hooks.py
Fix a discrepancy between the documented lifecycle and the Python runner:  
- `on_llm_start` and `on_llm_end` now emit from `Runner.run()` consistently in both streaming and non-streaming flows.  
- Applies to `_get_new_response` and `_run_single_turn_streamed`.  
- Behavior now matches the public API docs and other SDKs.
---
- **Start:** `on_llm_start` fires immediately before an LLM request (sync/async/streaming).  
- **End:** `on_llm_end` fires only on **successful** completion (after final chunk in streaming).  
- **Error:** On exceptions, `on_llm_end` and `on_agent_end` are *not* emitted; errors propagate. This preserves current semantics.
**Hook ordering** (because run hooks and agent hooks dispatch concurrently):  
- Start → RunHook, then AgentHook  
- End → AgentHook, then RunHook …
> fix(run): fire on_llm_start / on_llm_end in Runner.run() for streaming & non-streaming (aligns with docs)

- docs/usage.md
Even though I wrote this page originally, it got confused about how session usage tracking works. The docs incorrectly suggested `Runner.run()` returns cumulative usage across sessions, when it actually returns per-run usage only.
Updated to clarify that each run returns its own usage metrics, and sessions just re-feed conversation history as input (which affects token counts but not usage aggregation).
> Docs: Fix confusing session usage docs

- examples/tools/web_search_filters.py
- pyproject.toml
- src/agents/models/openai_responses.py
- src/agents/tool.py
- uv.lock
This pull request resolves #1640
> fix: Fix #1640 openai package breaking changes

- src/agents/realtime/session.py
```
runner = RealtimeRunner(
starting_agent=RealtimeAgent(
name="realtime agent",
tools=tools,
)
)
model_config = {"initial_model_settings": {"instructions": "Specific instructions"}}
await runner.run(model_config = model_cfg)
```
I would assume we first create the runner with an agent.  
And then when actually running we can add specific instructions.  
Currently these instructions are ignored.
> Fix instructions not being applied

- src/agents/_debug.py
- tests/test_debug.py
DONT_LOG_MODEL_DATA and DONT_LOG_TOOL_DATA constants' default values differ from the behaviors clearly stated in the documentation (code comments).
> Fix a bug where the default behavior of loading the debug flag differs from the documentation

- src/agents/realtime/session.py
- tests/realtime/test_session.py
Resolves #1661
- merge run and initial realtime session settings when constructing a session
- reuse the merged base when recomputing settings so the active voice is preserved on handoffs or agent updates
- add a regression test that ensures the initial voice and output audio format remain intact when refreshing session settings
- make format
- make lint
- make mypy *(fails: optional dependencies numpy, sqlalchemy, and litellm are not installed in the test environment)*
- make tests *(fails: optional dependencies numpy and litellm are not installed in the test environment)*
> fix: #1661 Preserve realtime session voice settings when updating agents

- src/agents/run.py
Resolves #1699, and fixes session history duplication introduced in #1550. 
**Problem**:
When using sessions, the second `Runner.run()` call was saving combined input (history + new user input) instead of just the new user input, causing session history to be re-saved and duplicated.
**Root cause**:
Line 442 was saving `original_input` which contained the combined session history, not the actual user input.
**Fix**:
Separate `original_user_input` from `prepared_input` (which includes session history). Save only the new user input to prevent duplication.
```python
prepared_input = await self._prepare_input_with_session(input, session)
await self._save_result_to_session(session, prepared_input, [])  # ❌ saves history too
original_user_input = input
prepared_input = await …
```
> Fix session history duplication after PR #1550

- .github/workflows/tests.yml
The `old_version_tests` target was failing in CI because it creates a separate Python 3.9 environment (`.venv_39`) that doesn't inherit dependencies from the main environment. Some tests import from modules that require optional dependencies.
I just added a step to explicitly install all dependencies for the Python 3.9 environment before running the tests.
> Fix CI failure in `make old_version_tests`

- src/agents/result.py
There was a critical race condition in the `RunResultStreaming.stream_events()` method in `src/agents/result.py` that caused premature cancellation of session operations during streaming.
**Issues**: Closes #1658 - Resolves race condition causing incomplete session state during streaming operations.
- The `_cleanup_tasks()` method was being called immediately after the streaming loop finished
- This cleanup occurred **before** the main execution task (`_run_impl_task`) completed
- As a result, `session.add_items()` calls were being cancelled prematurely
- Session state was not being fully recorded, leading to incomplete conversation history
- Session memory functionality was unreliable during streaming operations
- Conversation state could be lost or incomplete
- Race condition occurred …
> Fixed Race Condition in RunResultStreaming.stream_events() Method

- src/agents/tracing/spans.py
- src/agents/voice/models/openai_stt.py
- tests/voice/test_openai_stt.py
Fixes https://github.com/openai/openai-agents-python/issues/1755
The streamed voice demo fails to run because the STT events have changed as part of Realtime GA.  
This PR migrates the STT voice model to be consistent with GA.
As such, this is a BREAKING change for those who want to use beta servers. 
1. Use GA event name `session.update` (instead of `transcription_session.update`) and GA session payload shape (like nested `audio.input` with PCM format object).
2. Update STT tests for the same.
3. Misc: Lint for `src/agents/tracing/spans.py`
The demo works as expected and all tests/lint/type-checks pass.
> feat(voice)!: migrate STT streaming to match GA Realtime API

- src/agents/extensions/handoff_filters.py
- tests/test_extension_filters.py
When `store=False` and `handoff_filters.remove_all_tools` is used during a handoff, the filter currently removes: `HandoffCallItem` and   `HandoffOutputItem`... But it does **not** remove the corresponding `ReasoningItem`.
Since `store=False` means items are not persisted on the server side, the Responses API fails because the `ReasoningItem` is still present, but its referenced item has already been removed. This leads to a 404 error:
```
Error getting response: Error code: 404 - {'error': {'message': "Item with id 'rs_xxxx' not found. Items are not persisted when `store` is set to false. Try again with `store` set to true, or remove this item from your input.", 'type': 'invalid_request_error', 'param': 'input', 'code': None}}.
```
This PR fixes: …
> fixl: #1668 Handoffs with gpt-5* model + store=False + remove_all_tools fails due to 404 error response

- src/agents/util/_transforms.py
This PR adds a warning when agent names contain non-alphanumeric characters.  
Such names are converted to underscores (`_`) when used as default function names in handoff or `agent.as_tool`.
In these cases, non-English or symbolic names may turn into the same function name (e.g. `____`).  
The server does not raise an error, but handoffs will fail silently or tools may be overwritten.  
This is frustrating for developers when testing handoffs, as they will never be routed to the correct agent.
```
from agents import Agent, ModelSettings, Runner, handoff
agent2 = Agent(
name="風林火山 Agent",
model="gpt-5-mini",
instructions="You always answer: tree and mountain.",
)
agent3= Agent(
name="疾風迅雷 Agent",
model="gpt-5-mini",
instructions="You always answer: wind and thunder.",
)
agent = Agent( …
```
> Add warning for agent names that transform into conflicting function names

- examples/basic/stream_function_call_args.py
- Replaced plain type hints with Annotated to provide parameter descriptions
- Marked dependencies as Optional[list[str]] for flexibility
- Improved function docstrings for consistency and clarity
- No changes to streaming logic, only schema/metadata enhancements
> Enhance function tool schemas with Annotated types

- src/agents/models/chatcmpl_converter.py
- tests/test_anthropic_thinking_blocks.py
In the case of Anthropic Claude with extended thinking, this ensures that existing text content is properly converted to content array format before appending thinking blocks, preventing overwriting of original assistant message content.
This happens in a rare case where there is a (output text, thinking block, tool call) all in one response. Error message is like below:
```
litellm.BadRequestError: BedrockException - {"message":"The model returned the following errors: messages.1.content.49: `thinking` or `redacted_thinking` blocks in the latest assistant message cannot be modified. These blocks must remain as they were in the original response."}
```
The error is misleading because the actual reason is because we didn't provide the text content along side the thinking blocks.
This …
> fix(chatcmpl): preserve text content when adding Anthropic thinking blocks to tool calls

- examples/basic/lifecycle_example.py
- src/agents/realtime/session.py
- src/agents/tool_context.py
- tests/test_agent_as_tool.py
- tests/test_function_tool.py
- tests/test_function_tool_decorator.py
Currently, the `RunHooks` lifecycle (`on_tool_start`, `on_tool_end`) exposes the `Tool` and `ToolContext`, but does not include the actual arguments passed to the tool call. 
resolves https://github.com/openai/openai-agents-python/issues/939
This implementation is inspired by [PR #1598](https://github.com/openai/openai-agents-python/pull/1598).
* Add a new `tool_arguments` field to `ToolContext` and populate it via from_agent_context with tool_call.arguments.
* Update `lifecycle_example.py` to demonstrate tool_arguments in hooks
* Unlike the proposal in [PR #253](https://github.com/openai/openai-agents-python/issues/253), this solution is not expected to introduce breaking changes, making it easier to adopt.
> Add tool call arguments in ToolContext for RunHooks

- src/agents/extensions/models/litellm_model.py
- src/agents/models/chatcmpl_converter.py
- tests/test_extended_thinking_message_order.py
Resolves #1797 
This fixes the issue where conversation histories with extended thinking could have tool_result messages appearing before their corresponding tool_use messages, causing Anthropic API rejections.
**What was happening:**
- Reasoning blocks between tool calls caused the converter to create malformed message sequences
- Multiple consecutive assistant messages with tool calls weren't getting paired with their results properly
- Anthropic API requires strict tool_use → tool_result ordering
**The fix:**
- Added `_fix_tool_message_ordering()` method that only activates when `preserve_thinking_blocks=True`
- Analyzes the entire conversation to identify tool call/result pairs
- Reconstructs messages ensuring proper tool_use → tool_result sequencing
- Handles edge cases like …
> Fix extended thinking bug by reordering tool messages

- examples/basic/lifecycle_example.py
We didn't have working examples of agent hooks in this repo. This pull request adds simple agent hooks to the lifecycle_example.py.
> Add agent hooks to lifecycle_example

- docs/agents.md
- docs/voice/quickstart.md
- examples/voice/streamed/my_workflow.py
This pull request updates the models used in document pages.
> Update models in docs

- src/agents/models/chatcmpl_converter.py
For input_file the  `filename` parameter was recently made required in https://github.com/openai/openai-agents-python/pull/1513. 
This conflicts with many models outside of OpenAI, which do not require it.
This PR makes `filename` optional again to improve compatibility across the ecosystem. 
For gpt* models, the server already handles missing filename errors, making the current client-side validation redundant.
> fix: making input_file's filename optional in code for supporting non-OpenAI models

- examples/mcp/streamablehttp_custom_client_example/README.md
- examples/mcp/streamablehttp_custom_client_example/main.py
- examples/mcp/streamablehttp_custom_client_example/server.py
- src/agents/mcp/server.py
- src/agents/mcp/util.py
- tests/mcp/test_streamable_http_client_factory.py
This PR enables the customization of the MCP http client adding a new parameter httpx_client_factory to MCPServerStreamableHttpParams.
Fixes #1829
> feat: #1829 add httpx_client_factory to MCPServerStreamableHttp initialization options

- docs/running_agents.md
- src/agents/run.py
- tests/fake_model.py
- tests/test_agent_runner.py
This PR fixes incorrect behavior when using `conversation_id` or `previous_response_id` during internal multi-turn calls, i.e. when function calling is involved.
It provides better support for the OpenAI Conversation state feature, as described in the https://platform.openai.com/docs/guides/conversation-state?api-mode=responses, aligning with the intended API design.
Resolved: https://github.com/openai/openai-agents-python/issues/1789
- When using **conversation_id**, the runner resent all items on every turn, which caused server-side duplicate item error. 
- When using **previous_response_id**, the SDK also resent all items and the `previous_response_id` was not updated across internal loops. This led to duplicated items and wasted bandwidth, even though it did not trigger errors …
> fix: #1789 Fix multi-turn handling for conversation_id and previous_response_id: only send new items

- docs/tools.md
This PR improves the formatting consistency in the tools documentation by standardizing the list item
format.
Changes made:
- Updated list formatting in the "Output extraction" section from -- prefixes to proper -    (dash with 3
spaces) format
- Updated list formatting in the "Enabling/disabling tools" section from -- prefixes to proper -    format
- These changes ensure consistent markdown formatting throughout the document
Files changed:
- docs/tools.md
Before:
After:
> docs: improve formatting consistency in tools documentation
