openai/openai-agents-python

src/agents/tool.py

Fix: remove unreached code in tool.py

---

README.md
docs/tracing.md

- Updating readme and tracing docs to include Keywords AI

Adding Keywords AI as a trace processor

---

docs/tracing.md

Fix the typo in tracing.md #107

Bug #107. fix typo in tracing.md

---

README.md
examples/basic/hello_world_jupyter.py

To address #77, adding a Jupyter hello world example and a link from the Readme

Adding Jupyter notebook example

---

src/agents/tracing/processors.py

Update tracing docs to be correct

---

docs/tracing.md

LangChain employee/maintainer, happy to make edits to our docs/integrations if needed.

docs: List LangSmith tracing integration

---

README.md
pyproject.toml

Release a new version with voice support

v0.0.6 (voice support)

---

tests/test_agent_tracing.py
tests/test_responses_tracing.py
tests/test_tracing.py
tests/testing_processor.py
uv.lock

Following https://github.com/openai/openai-agents-python/pull/261

Replace remaining uses of `fetch_ordered_spans` and `fetch_traces` for stronger tests

---

docs/tracing.md

Hi,
I’ve added a link to Weights & Biases integration docs. Let me know if there’s anything I need to change.

Add Weights & Biases to tracing docs

---

examples/mcp/filesystem_example/README.md
examples/mcp/git_example/README.md
examples/mcp/git_example/main.py

- Adding new example showing a single agent interacting with local MCP server for git

Adding Git MCP server example

---

docs/tracing.md

Monocle is an open source tracing and eval for GenAI apps.

Update tracing.md - Added Okahu-Monocle

---

src/agents/agent.py

close https://github.com/openai/openai-agents-python/issues/440

docs: Make default model clear

---

pyproject.toml

These two deps are only used in development/examples

Move dev-only deps to dev section

---

.github/workflows/tests.yml

Was not running on my stacked PRs.

Run CI on all commits, not just ones on main

---

src/agents/models/chatcmpl_converter.py
src/agents/models/openai_chatcompletions.py
tests/test_openai_chatcompletions.py
tests/test_openai_chatcompletions_converter.py
tests/test_tool_converter.py

Small refactor for rest of stack.
---
* #524
* #523
* __->__ #522

Extract chat completions conversion code into helper

---

src/agents/models/chatcmpl_stream_handler.py
src/agents/models/openai_chatcompletions.py

Small refactor.
---
* #524
* __->__ #523

Extract chat completions streaming helpers

---

mkdocs.yml

Easy linking back to the repo, plus some social proof (stars/forks etc).

Show repo name/data in docs

---

examples/financial_research_agent/main.py

Simply resolving the path error

Examples: Fix financial_research_agent instructions

---

pyproject.toml
uv.lock

Addresses https://github.com/openai/openai-agents-python/issues/614

Update litellm version

---

src/agents/extensions/models/litellm_model.py

fix Gemini token validation issue with LiteLLM

---

docs/ja/tracing.md
docs/tracing.md

This PR adds Portkey AI as a tracing provider. Portkey helps you take your OpenAI agents from prototype to production.
Portkey turns your experimental OpenAI Agents into production-ready systems by providing:
- Complete observability of every agent step, tool use, and interaction
- Built-in reliability with fallbacks, retries, and load balancing
- Cost tracking and optimization to manage your AI spend
- Access to 1600+ LLMs through a single integration
- Guardrails to keep agent behavior safe and compliant
- Version-controlled prompts for consistent agent performance
Towards #786

Add Portkey AI as a tracing provider

---

examples/basic/prompt_template.py
pyproject.toml
src/agents/__init__.py
src/agents/agent.py
src/agents/extensions/models/litellm_model.py
src/agents/models/interface.py
src/agents/models/openai_chatcompletions.py
src/agents/models/openai_responses.py
src/agents/prompts.py
src/agents/run.py
src/agents/tool_context.py
tests/fake_model.py
tests/models/test_litellm_chatcompletions_stream.py
tests/test_agent_prompt.py
tests/test_openai_chatcompletions.py
tests/test_openai_chatcompletions_stream.py
tests/test_responses_tracing.py
tests/voice/test_workflow.py
uv.lock

Add support for the new openai prompts feature.

Prompts support

---

src/agents/__init__.py

This PR fixes a duplicated line in `__init__.py`

Remove duplicate entry from `__init__.py`

---

examples/agent_patterns/llm_as_a_judge.py

Updated the evaluator agent’s instructions in llm_as_a_judge.py to prevent infinite evaluation loops. The agent is now instructed to provide a final evaluation after 5 attempts, allowing approval if the story outline is good enough, even if it is not perfect.

Updated llm_as_a_judge.py

---

docs/ref/tool_context.md
docs/tools.md
mkdocs.yml
src/agents/_run_impl.py
src/agents/tool_context.py
tests/test_function_tool.py
tests/test_function_tool_decorator.py

Original commit changeset: befe19db273a
causing test failures, so reverting

Back out "enhancement: Add tool_name to ToolContext to support shared tool handlers (#1043)"

---

tests/mcp/test_mcp_util.py

Unbreak tests

---

.github/workflows/codex.yml

Use real codex action

---

pyproject.toml
src/agents/models/chatcmpl_stream_handler.py
tests/voice/test_workflow.py
uv.lock

This pull request resolves #1227

Fix #1227 Chat Completions model fails to handle streaming with openai 1.97.1+

---

src/agents/__init__.py

This pull request resolves #1277

Fix #1277 missing StopAtTools and ToolsToFinalOutputFunction in agents module

---

examples/basic/lifecycle_example.py

Fixed a type safety issue where user input was being used as a string without conversion to integer, which could cause runtime errors and type mismatches (in `lifecycle_example.py`).
The code was using `input()` which returns a string, but then using it directly in the f-string without converting it to an integer. This could cause:
- Type mismatches when the string is passed to functions expecting integers
- Runtime errors when users enter non-numeric input
- Inconsistent behavior with the function signature expectations
Added proper input validation and type conversion:
- Wrapped the input processing in a try-except block
- Convert user input to integer using `int(user_input)`
- Added error handling for invalid input with user-friendly message
- Used the converted integer value in the …

Add input validation and type conversion for user input

---

src/agents/model_settings.py

This pull request resolves #1494

Fix #1494 by adding a link to Responses API documentation

---

docs/agents.md

docs: Fix #1625 code snippet error

---

docs/running_agents.md

I was reading through some docs and code examples, I believe this particular example is missing a `threads_id` variable definition.

Code snippet error in "Running Agents" document

---

docs/llms-full.txt
docs/llms.txt

This pull request aims to resolve #556

fix: #556 add llms.txt / llms-full.txt
